In [1]:
import tensorflow as tf
import numpy as np
import h5py
import matplotlib.pyplot as plt

import models.graph_nn as grap

# data preprocessing

In [7]:
def normalized_adjacency(A):

    D = np.array(np.sum(A, axis=2), dtype=np.float32) # compute outdegree (= rowsum)
    D = np.nan_to_num(np.power(D,-0.5), posinf=0, neginf=0) # normalize (**-(1/2))
    D = np.diag(D.flatten()) # and diagonalize
    
    return np.matmul(D, np.matmul(A_tilde, D))    


In [2]:
def make_adjacencies(particles):
    real_p = particles[:,:,0] > 0
    adjacencies = (real_p[:,:,np.newaxis] * real_p[:,np.newaxis,:]).astype('int')
    return adjacencies

# load data

In [3]:
filename = '/home/kinga/dev/datasamples/L1_anomaly_challenge/background_training_1M.h5'
ff = h5py.File(filename, 'r')
particles = np.asarray(ff.get('Particles'))

In [4]:
particles.shape

(1000000, 19, 4)

In [5]:
# features: array([b'Pt', b'Eta', b'Phi', b'Class'], dtype='|S5')
particles = particles[:1000]

In [6]:
adjacencies = make_adjacencies(particles)
A_tilde = normalized_adjacency(adjacencies)

In [8]:
adjacencies.shape

(1000, 19, 19)

In [9]:
adjacencies_tmp = adjacencies[:2]

In [11]:
adjacencies_tmp.shape

(2, 19, 19)

In [12]:
D = np.array(np.sum(adjacencies_tmp, axis=2), dtype=np.float32) # compute outdegree (= rowsum)

In [13]:
D.shape

(2, 19)

In [14]:
D

array([[3., 0., 0., 0., 0., 3., 0., 0., 0., 3., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [2., 0., 0., 0., 0., 2., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.]], dtype=float32)

In [20]:
D = np.nan_to_num(np.power(D,-0.5), posinf=0, neginf=0)

/home/kinga/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in power
  """Entry point for launching an IPython kernel.


In [21]:
D.shape

(2, 19)

In [22]:
D

array([[0.57735026, 0.        , 0.        , 0.        , 0.        ,
        0.57735026, 0.        , 0.        , 0.        , 0.57735026,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ],
       [0.70710677, 0.        , 0.        , 0.        , 0.        ,
        0.70710677, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        ]], dtype=float32)

In [30]:
D_diag = np.diagflat(D)

In [31]:
D_diag.shape

(38, 38)

In [27]:
x = np.array([1,2,3],)

In [28]:
np.diag(x)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])